[package]
name = "notes_app"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = "0.6.3"
dioxus-web = "0.6.3"
gloo-storage = "0.3.0"
js-sys = "0.3.77"
serde = { version = "1.0.219", features = ["derive"] }
