[application]

[web.app]

# HTML title tag content
title = "cms"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = [
    "https://cdn.quilljs.com/1.3.6/quill.snow.css",
    "/assets/custom.css"
]

# Additional JavaScript files
script = [
    "https://cdn.quilljs.com/1.3.6/quill.min.js"
]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
