FROM jetpackio/devbox:latest

# Installing your devbox project
WORKDIR /code
USER root:root
RUN mkdir -p /code && chown ${DEVBOX_USER}:${DEVBOX_USER} /code
USER ${DEVBOX_USER}:${DEVBOX_USER}
COPY --chown=${DEVBOX_USER}:${DEVBOX_USER} devbox.json devbox.json
COPY --chown=${DEVBOX_USER}:${DEVBOX_USER} devbox.lock devbox.lock


ENV PATH="/home/devbox/.bun/bin:/home/devbox/.local/bin:$PATH"
RUN devbox run -- echo "Installed Packages."

RUN devbox shellenv --init-hook >> ~/.profile
