[package]
name = "lppy"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.7.5", features = ["csr"] }
leptos_meta = "0.7.5"
stylance = "0.5.4"
wasm-bindgen = "0.2.100"
